---

- name: Copy docker-compose.yml
  template: src=docker-compose.yml dest=/root

  # TODO: ansible needs to start the containers as well.
  # Currently that is still manual 'doco up'

- name: Create influxb databases
  influxdb_database:
    hostname: "localhost"
    database_name: "{{ item.db }}"
    state: present
    username: admin
    password: "{{influxdb_admin_password}}"
  with_items: "{{influxdb_users}}"

- name: Create influx users with POST
  uri:
    url: "http://localhost:8086/query?q={{'create user '|urlencode}}{{item.username}}{{' WITH PASSWORD '|urlencode}}'{{item.password}}'"
    method: GET
    user: admin
    password: "{{influxdb_admin_password}}"
  with_items: "{{influxdb_users}}"

- name: Grant ALL on db with POST
  uri:
    url: "http://localhost:8086/query?q={{'GRANT ALL ON '|urlencode}}{{item.db}}{{' TO '|urlencode}}{{item.username}}"
    method: GET
    user: admin
    password: "{{influxdb_admin_password}}"
  with_items: "{{influxdb_users}}"
